---

- name: Update apt cache
  apt:
    update_cache: yes
  become: yes

- name: Install required packages
  package:
    name:
      - curl
      - tar
      - unzip
    state: present
  become: yes
  
- name: Check if Github Service is already installed
  service:
    name: actions.runner.BenTheBuilder-MSFTLabs-lab-api.gitops-lab-runner.service
    state: started
  register: github_service

- name: Create installation directory
  file:
    path: "{{ INSTALL_DIR }}"
    state: directory
    mode: '0755'
  when: github_service is not defined or github_service is failed

- name: Download GitHub Runner Agent
  get_url:
    url: "{{ GH_RUNNER_URL }}"
    dest: "/tmp/{{ GH_RUNNER_ARCHIVE }}"
  when: github_service is not defined or github_service is failed

- name: Extract GitHub Runner Agent
  unarchive:
    src: "/tmp/{{ GH_RUNNER_ARCHIVE }}"
    dest: "{{ INSTALL_DIR }}"
    remote_src: yes
  when: github_service is not defined or github_service is failed

- name: Configure GitHub Runner
  command: "./config.sh --unattended --url {{ GH_REPO_URL }} --pat {{ GITHUB_TOKEN }} --name {{ GH_RUNNER_NAME }}"
  args:
    chdir: "{{ INSTALL_DIR }}"
  when: github_service is not defined or github_service is failed

- name: Install GitHub Runner service
  command: "./svc.sh install"
  args:
    chdir: "{{ INSTALL_DIR }}"
  become: yes
  when: github_service is not defined or github_service is failed

- name: Start GitHub Runner service
  command: "./svc.sh start"
  args:
    chdir: "{{ INSTALL_DIR }}"
  become: yes
  when: github_service is not defined or github_service is failed