---
- name: Configure Apache Web Server
  hosts: webservers
  become: yes
  vars:
    apache_package: apache2
    apache_service: apache2

  tasks:

    - name: Install Apache
      apt:
        name: "{{ apache_package }}"
        state: present
      notify: Restart Apache

    - name: Ensure Apache service is running
      service:
        name: "{{ apache_service }}"
        state: started
        enabled: yes
      register: apache_status

  handlers:

    - name: Restart Apache
      service:
        name: "{{ apache_service }}"
        state: restarted



https://github1s.com/BenTheCloudGuy/msft-intro-to-gitops