---
- name: Update apt cache
  apt:
    update_cache: yes
  become: yes

- name: Install required dependencies
  package:
    name: 
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
  become: yes

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: yes

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
  become: yes

- name: Install Docker
  apt:
    name: "{{ docker_packages }}"
    state: present
  become: yes

- name: Ensure Docker service is running
  service:
    name: docker
    state: started
    enabled: yes
  become: yes

- name: Add user to Docker group
  user:
    name: "docker"
    groups: docker
    append: yes
  become: yes

- name: Verify Docker installation
  command: "docker --version"
  register: docker_version
  changed_when: false
