---

- hosts: ghrunners
  gather_facts: yes
  roles:
    - role: ghrunner
    - role: terraform
    - role: ansible
    - role: docker

  tasks:
    - name: Ensure Private SSH Key Exists on Remote Server
      copy:
        src: ~/.ssh/ansible
        dest: /home/{{ ansible_user }}/.ssh/ansible
        mode: '0600'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
      become: yes

    - name: Ensure Public SSH Key Exists on Remote Server
      copy:
        src: ~/.ssh/ansible.pub
        dest: /home/{{ ansible_user }}/.ssh/ansible.pub
        mode: '0644'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
      become: yes

    - name: Ensure .ssh directory permissions are correct
      file:
        path: /home/{{ ansible_user }}/.ssh
        state: directory
        mode: '0700'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
      become: yes

    - name: Install AzCli
      package:
        name: azure-cli
        state: present
      become: yes