---
- name: Update apt cache
  apt:
    update_cache: yes
  become: yes

- name: Ensure required dependencies are installed
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - software-properties-common
    - python3
    - python3-pip
  become: yes

- name: Add Ansible PPA
  apt_repository:
    repo: "ppa:ansible/ansible"
    state: present
  become: yes

- name: Install Ansible
  apt:
    name: ansible
    state: present
  become: yes

- name: Verify Ansible installation
  command: "ansible --version"
  register: ansible_version
  changed_when: false
