name: Build and Push Docker Image

on:
  push:
    paths:
      - 'docker/**'
      - .github/workflows/docker-build.yml

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          cd ${{ github.workspace }}/docker
          REPO_OWNER_LC=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          docker build -t ghcr.io/$REPO_OWNER_LC/demo-api .
          docker push ghcr.io/$REPO_OWNER_LC/demo-api:latest